// Biblioteka ćwiczeń; animacje ruchu są w moves.js.
// p = mięśnie główne, s = pomocnicze (klucze z MUSCLES). kg = krok zmiany ciężaru w kg (ćwiczenie z obciążeniem), kgOpis = dopisek do ciężaru, np. „na hantel”.
// \u00AD to miejsce, w którym długa nazwa może się złamać (z łącznikiem) w wąskiej kolumnie legendy; bez niego procent wychodzi poza kolumnę.
globalThis.MUSCLES = {
  chest: 'klatka piersiowa', shoulders: 'barki', biceps: 'bicepsy', triceps: 'tricepsy', forearms: 'przed\u00ADramiona',
  abs: 'brzuch', obliques: 'skośne brzucha', traps: 'czworo\u00ADboczne', lats: 'naj\u00ADszersze grzbietu', midback: 'środek pleców',
  lowerback: 'pro\u00ADstow\u00ADniki grzbietu', glutes: 'pośladki', quads: 'czworo\u00ADgłowe ud', hamstrings: 'dwu\u00ADgłowe ud',
  adductors: 'przy\u00ADwodzi\u00ADciele', calves: 'łydki',
};

globalThis.EXERCISES = {
  'podciaganie': {
    name: 'Podciąganie nachwytem', p: ['lats'], s: ['biceps', 'midback', 'forearms'],
    steps: ['Chwyt nachwytem, trochę szerzej niż barki. Start z pełnego zwisu, łokcie proste.',
      'Najpierw ściągnij łopatki w dół, potem ciągnij łokcie w stronę żeber.',
      'Broda nad drążek, klatka blisko drążka.',
      'Opuszczaj się pod kontrolą aż do pełnego zwisu.'],
    tips: ['Bez bujania i kopania nogami: nogi razem, brzuch i pośladki napięte.',
      'Liczy się tylko pełne powtórzenie, od prostych łokci do brody nad drążkiem.'],
  },
  'podciaganie-podchwyt': {
    name: 'Podciąganie podchwytem', p: ['lats', 'biceps'], s: ['midback', 'forearms'],
    steps: ['Chwyt podchwytem (dłonie do siebie) na szerokość barków, pełny zwis.',
      'Ściągnij łopatki i ciągnij łokcie w dół wzdłuż tułowia.',
      'Broda nad drążek, pół sekundy pauzy.',
      'Powoli wróć do pełnego zwisu.'],
    tips: ['Zwykle łatwiejsze niż nachwyt, dobre do budowania liczby powtórzeń.'],
  },
  'podciaganie-guma': {
    name: 'Podciąganie z gumą', p: ['lats'], s: ['biceps', 'midback'],
    steps: ['Zawiąż gumę na drążku (pętla przez pętlę) i włóż w nią stopę albo kolano.',
      'Chwyt jak w zwykłym podciąganiu (nachwyt lub podchwyt, patrz notatka), pełny zwis.',
      'Podciągnij się, broda nad drążek.',
      'Opuszczaj się wolno, przez 2–3 s.'],
    tips: ['Gumę dobierz tak, żeby ostatnie 2 powtórzenia były trudne, ale czyste.',
      'Co kilka tygodni cieńsza guma. Cel: podciąganie bez pomocy.'],
  },
  'podciaganie-negatyw': {
    name: 'Negatywy podciągania', p: ['lats'], s: ['biceps', 'midback', 'forearms'],
    steps: ['Wejdź nad drążek z podskoku albo z podwyższenia, broda nad drążkiem.',
      'Opuszczaj się jak najwolniej (cel: 5 s) aż do pełnego zwisu.',
      'Stań, weź oddech i powtórz.'],
    tips: ['Kontroluj cały zakres, także końcówkę przy prostych łokciach.',
      'Jeśli nie trzymasz tempa, skróć serię zamiast „spadać”.'],
  },
  'podciaganie-lopatek': {
    name: 'Podciąganie łopatek', p: ['traps'], s: ['lats', 'midback'],
    steps: ['Pełny zwis nachwytem. Łokcie proste przez całe ćwiczenie.',
      'Ściągnij łopatki w dół i do tyłu, ciało uniesie się o kilka centymetrów.',
      'Przytrzymaj 1 s i powoli wróć do zwisu.'],
    tips: ['Ruch tylko z łopatek, bez zginania łokci.',
      'To podstawa zdrowych barków i czystego podciągania.'],
  },
  'zwis': {
    name: 'Zwis na drążku', p: ['forearms'], s: ['lats', 'shoulders'],
    steps: ['Chwyć drążek nachwytem na szerokość barków.',
      'Zawiśnij na prostych rękach, nogi razem.',
      'Oddychaj spokojnie i trzymaj do końca czasu.'],
    tips: ['Wersja aktywna: lekko ściągnij łopatki, barki z dala od uszu.',
      'Wzmacnia chwyt i odciąża kręgosłup.'],
  },
  'trx-wioslowanie': {
    name: 'TRX wiosłowanie', p: ['midback'], s: ['lats', 'biceps', 'shoulders'],
    steps: ['Chwyć uchwyty i odchyl się do tyłu na prostych rękach, ciało proste jak deska.',
      'Ściągnij łopatki i przyciągnij klatkę do dłoni, łokcie blisko tułowia.',
      'Sekunda pauzy na górze, potem powoli do prostych rąk.'],
    tips: ['Trudność ustawiasz kątem: stopy bliżej punktu zaczepienia to trudniej.',
      'Biodra nie opadają, pośladki napięte.'],
  },
  'wioslowanie-australijskie': {
    name: 'Wiosłowanie australijskie', p: ['midback'], s: ['lats', 'biceps'],
    steps: ['Połóż się pod niskim drążkiem (na wysokości bioder), chwyć nachwytem szerzej niż barki.',
      'Ciało proste od pięt do głowy, pięty na ziemi.',
      'Przyciągnij klatkę do drążka, ściągając łopatki, i powoli opuść.'],
    tips: ['Łatwiej: ugięte kolana. Trudniej: nogi na podwyższeniu.'],
  },
  'dipy': {
    name: 'Dipy na poręczach', p: ['triceps', 'chest'], s: ['shoulders'],
    steps: ['Podpór na prostych rękach, barki w dół (z dala od uszu), nogi lekko ugięte z tyłu.',
      'Opuszczaj się z lekkim pochyleniem tułowia, aż łokcie zegną się do ok. 90°.',
      'Wypchnij się do pełnego wyprostu łokci.'],
    tips: ['Nie schodź niżej niż 90°, bo to przeciąża barki.',
      'Łokcie prowadź do tyłu, nie na boki.'],
  },
  'dipy-negatyw': {
    name: 'Negatywy dipów', p: ['triceps', 'chest'], s: ['shoulders'],
    steps: ['Wejdź do podporu na prostych rękach, z podskoku albo z podwyższenia.',
      'Opuszczaj się wolno (cel: 4 s) do zgięcia łokci ok. 90°.',
      'Stań, wróć do podporu i powtórz.'],
    tips: ['Barki nisko przez cały ruch.',
      'Jeśli czujesz przód barku, zmniejsz zakres.'],
  },
  'podpor-porecze': {
    name: 'Podpór na poręczach', p: ['triceps', 'shoulders'], s: ['chest', 'abs'],
    steps: ['Wejdź na poręcze, ręce proste, łokcie zablokowane.',
      'Barki mocno w dół, klatka do przodu, brzuch napięty.',
      'Trzymaj pozycję do końca czasu.'],
    tips: ['Nie zapadaj się w barkach, szyja długa.',
      'Przygotowuje barki i nadgarstki do dipów.'],
  },
  'pompki': {
    name: 'Pompki', p: ['chest'], s: ['triceps', 'shoulders', 'abs'],
    steps: ['Dłonie trochę szerzej niż barki, ciało proste od głowy do pięt.',
      'Opuść klatkę prawie do podłogi, łokcie ok. 45° od tułowia.',
      'Wypchnij się do prostych rąk.'],
    tips: ['Brzuch i pośladki napięte, biodra nie opadają.',
      'Łatwiej: dłonie na podwyższeniu. Trudniej: nogi na podwyższeniu.'],
  },
  'pompki-trx': {
    name: 'Pompki na TRX', p: ['chest'], s: ['triceps', 'shoulders', 'abs'],
    steps: ['Chwyć uchwyty, stań tyłem do zaczepienia i pochyl się do przodu z prostymi rękami przed klatką.',
      'Ciało proste. Zginaj łokcie, aż dłonie znajdą się przy klatce.',
      'Wypchnij się do startu, pilnując, żeby uchwyty się nie rozjeżdżały.'],
    tips: ['Im bardziej poziomo, tym trudniej.',
      'Panowanie nad chwiejnymi uchwytami to sedno tego ćwiczenia.'],
  },
  'pompki-waskie': {
    name: 'Pompki wąskie', p: ['triceps'], s: ['chest', 'shoulders'],
    steps: ['Dłonie pod barkami albo bliżej, palce do przodu.',
      'Opuszczaj się z łokciami blisko tułowia.',
      'Wypchnij się do prostych rąk.'],
    tips: ['Mocniej pracuje triceps, co przygotowuje do dipów.',
      'Nie rozkładaj łokci na boki.'],
  },
  'pompki-nogi-wyzej': {
    name: 'Pompki z nogami wyżej', p: ['chest', 'shoulders'], s: ['triceps'],
    steps: ['Stopy na ławce albo podwyższeniu, dłonie na ziemi szerzej niż barki.',
      'Ciało proste, opuść klatkę do podłogi.',
      'Wypchnij się do prostych rąk.'],
    tips: ['Im wyższe podwyższenie, tym więcej pracy barków.', 'Nie łam bioder.'],
  },
  'pompki-na-podwyzszeniu': {
    name: 'Pompki na podwyższeniu', p: ['chest'], s: ['triceps', 'shoulders'],
    steps: ['Dłonie na ławce albo skrzyni, ciało proste, stopy na ziemi.',
      'Opuść klatkę do krawędzi, łokcie ok. 45°.',
      'Wypchnij się do prostych rąk.'],
    tips: ['Łatwiejsza wersja pompek: im wyżej dłonie, tym łatwiej.'],
  },
  'guma-rozciaganie': {
    name: 'Rozciąganie gumy (pull-apart)', p: ['shoulders'], s: ['midback', 'traps'],
    steps: ['Trzymaj gumę przed sobą na wysokości barków, ręce proste, chwyt na szerokość barków.',
      'Rozciągnij gumę na boki, ściągając łopatki, aż dotknie klatki.',
      'Wróć powoli.'],
    tips: ['Barki nisko, nie unoś ich do uszu.', 'Świetne na rozgrzewkę i postawę.'],
  },
  'guma-rotacja': {
    name: 'Rotacja zewnętrzna z gumą', p: ['shoulders'], s: [],
    steps: ['Przyczep gumę na wysokości łokcia i stań do niej bokiem.',
      'Łokieć przy boku (możesz włożyć zwinięty ręcznik), zgięty pod kątem 90°.',
      'Obracaj przedramię na zewnątrz, nie odrywając łokcia, i powoli wróć.'],
    tips: ['Lekki opór: to ćwiczenie ochronne dla barków, nie siłowe.',
      'Seria na jedną rękę, potem na drugą.'],
  },
  'guma-odwrotne-rozpietki': {
    name: 'Odwrotne rozpiętki z gumą', p: ['shoulders'], s: ['midback', 'traps'],
    steps: ['Przyczep gumę przed sobą na wysokości klatki albo trzymaj oba jej końce.',
      'Ręce lekko ugięte. Rozciągnij je na boki, ściągając łopatki.',
      'Sekunda pauzy i powoli wróć.'],
    tips: ['Pracują tylne części barków. Nie pomagaj sobie odchylaniem tułowia.'],
  },
  'kolana-porecze': {
    name: 'Unoszenie kolan na poręczach', p: ['abs'], s: ['triceps', 'shoulders'],
    steps: ['Podpór na poręczach na prostych rękach.',
      'Unieś kolana do klatki, lekko podwijając miednicę.',
      'Opuść nogi powoli, bez bujania.'],
    tips: ['Barki nisko przez całe ćwiczenie.', 'Trudniejsza wersja: proste nogi.'],
  },
  'kolana-zwis': {
    name: 'Unoszenie kolan w zwisie', p: ['abs'], s: ['forearms', 'lats'],
    steps: ['Zwis na drążku, łopatki lekko ściągnięte.',
      'Unieś kolana do klatki, podwijając miednicę.',
      'Opuść powoli, bez bujania.'],
    tips: ['Jeśli się bujasz, zrób krótką pauzę na dole.',
      'Następny krok: proste nogi do poziomu.'],
  },
  'plank': {
    name: 'Deska', p: ['abs'], s: ['shoulders', 'glutes'],
    steps: ['Oprzyj się na przedramionach, łokcie pod barkami.',
      'Ciało proste od głowy do pięt, pośladki i brzuch napięte.',
      'Trzymaj, oddychając spokojnie.'],
    tips: ['Biodra ani nie opadają, ani nie idą w górę.',
      'Lepiej krócej, ale w idealnej pozycji.'],
  },
  'deska-bokiem': {
    name: 'Deska bokiem', p: ['obliques'], s: ['abs', 'shoulders'],
    steps: ['Połóż się na boku, łokieć pod barkiem, nogi proste jedna na drugiej.',
      'Unieś biodra tak, żeby ciało tworzyło jedną linię.',
      'Trzymaj, a w następnej serii zmień stronę.'],
    tips: ['Biodra wypchnięte do przodu, pośladki nie uciekają do tyłu.'],
  },
  'trx-rollout': {
    name: 'TRX rollout', p: ['abs'], s: ['lats', 'shoulders'],
    steps: ['Chwyć uchwyty i stań tyłem do zaczepienia. Proste ręce trzymaj przed sobą, taśmy napięte.',
      'Pochylaj się do przodu, unosząc proste ręce nad głowę. Ciało proste jak deska.',
      'Wróć do startu siłą brzucha.'],
    tips: ['Nie wyginaj lędźwi, brzuch i pośladki mocno napięte.',
      'Trudność zależy od kąta. Zacznij bardziej pionowo.'],
  },
  'trx-kolana': {
    name: 'TRX przyciąganie kolan', p: ['abs'], s: ['shoulders'],
    steps: ['Stopy w pętlach TRX, podpór na prostych rękach jak do pompki.',
      'Przyciągnij kolana do klatki, lekko unosząc biodra.',
      'Wróć do prostej pozycji pod kontrolą.'],
    tips: ['Barki nad dłońmi. W pozycji startowej biodra nie opadają.'],
  },
  'dead-bug': {
    name: 'Dead bug', p: ['abs'], s: [],
    steps: ['Połóż się na plecach, ręce w górę, biodra i kolana zgięte pod kątem 90°.',
      'Dociśnij lędźwie do podłogi.',
      'Opuść jednocześnie przeciwną rękę i nogę, wróć i zmień stronę.'],
    tips: ['Lędźwie przez cały czas dociśnięte do podłogi. O to chodzi w tym ćwiczeniu.'],
  },
  'przysiad': {
    name: 'Przysiad', p: ['quads', 'glutes'], s: ['hamstrings'],
    steps: ['Stopy na szerokość bioder lub barków, palce lekko na zewnątrz.',
      'Zejdź w dół, cofając biodra, kolana idą w kierunku palców.',
      'Zejdź przynajmniej do poziomu ud i wstań, dociskając całe stopy.'],
    tips: ['Pięty na ziemi, plecy proste.'],
  },
  'przysiad-guma': {
    name: 'Przysiad z gumą', p: ['quads'], s: ['glutes', 'hamstrings'],
    steps: ['Stań na gumie, drugi koniec trzymaj przy barkach.',
      'Zrób przysiad jak zwykle: biodra do tyłu, kolana w kierunku palców.',
      'Wstań dynamicznie. Na górze guma stawia największy opór.'],
    tips: ['Grubsza guma albo krótszy chwyt to większy opór.'],
  },
  'trx-przysiad-wykroczny': {
    name: 'TRX przysiad wykroczny', p: ['quads', 'glutes'], s: ['hamstrings', 'adductors'],
    steps: ['Stań tyłem do zaczepienia, jedna stopa w pętli TRX za Tobą.',
      'Zegnij przednią nogę, cofając tylną w pętli. Tułów lekko pochylony.',
      'Wypchnij się przednią nogą w górę. Cała seria na jedną nogę, potem druga.'],
    tips: ['Kolano przedniej nogi nad stopą, nie ucieka do środka.',
      'Ciężar na przedniej nodze, tylna tylko pomaga w równowadze.'],
  },
  'przysiad-jednonoz': {
    name: 'Przysiad jednonóż na podwyższeniu', p: ['quads'], s: ['glutes'],
    steps: ['Stań jedną nogą na krawędzi ławki albo skrzyni, druga noga zwisa swobodnie.',
      'Trzymaj się TRX-a albo słupka dla równowagi.',
      'Opuść się powoli na jednej nodze tak nisko, jak kontrolujesz, i wstań.'],
    tips: ['Kolano nad palcami, pięta na podłożu.',
      'To droga do pistoletu. Z czasem coraz mniej pomagaj sobie rękami.'],
  },
  'wykroki': {
    name: 'Wykroki chodzone', p: ['quads', 'glutes'], s: ['hamstrings', 'calves'],
    steps: ['Zrób duży krok do przodu i opuść tylne kolano prawie do ziemi.',
      'Wypchnij się przednią nogą i przejdź do kolejnego kroku drugą nogą.',
      'Tułów wyprostowany, nogi na zmianę.'],
    tips: ['Przednie kolano nad stopą, nie ucieka do środka.'],
  },
  'mostek': {
    name: 'Mostek biodrowy', p: ['glutes'], s: ['hamstrings'],
    steps: ['Połóż się na plecach, kolana zgięte, stopy blisko pośladków.',
      'Unieś biodra, mocno napinając pośladki, aż ciało utworzy linię od kolan do barków.',
      'Sekunda pauzy i powoli w dół.'],
    tips: ['Pracują pośladki, nie lędźwie. Nie przeginaj pleców.'],
  },
  'mostek-jednonoz': {
    name: 'Mostek jednonóż', p: ['glutes'], s: ['hamstrings'],
    steps: ['Jak mostek, ale z jedną nogą wyprostowaną w górze.',
      'Unieś biodra, odpychając się piętą nogi podporowej. Biodra na równi.',
      'Sekunda pauzy i powoli w dół. Seria na jedną nogę, potem druga.'],
    tips: ['Miednica nie przechyla się na bok.'],
  },
  'guma-sklon': {
    name: 'Skłon z gumą (good morning)', p: ['hamstrings'], s: ['glutes', 'lowerback'],
    steps: ['Stań na gumie, drugi koniec załóż za kark na barki.',
      'Kolana lekko ugięte. Pochyl tułów do przodu z prostymi plecami (ruch z bioder).',
      'Wróć do pionu, napinając pośladki.'],
    tips: ['Plecy proste przez cały czas, nie zaokrąglaj ich.',
      'Rozciąganie z tyłu ud jest tu normalne.'],
  },
  'guma-uginanie-nog': {
    name: 'Uginanie nóg z gumą', p: ['hamstrings'], s: ['calves'],
    steps: ['Przyczep gumę nisko przed sobą, załóż pętlę na kostki i usiądź na ławce.',
      'Zegnij kolana, przyciągając pięty pod siebie.',
      'Powoli wróć do wyprostu.'],
    tips: ['Można też leżąc na brzuchu albo na plecach ze stopami w TRX.'],
  },
  'lydki-guma': {
    name: 'Wspięcia na palce z gumą', p: ['calves'], s: [],
    steps: ['Stań na gumie przednią częścią stóp, końce gumy trzymaj przy barkach.',
      'Wspnij się wysoko na palce, sekunda pauzy.',
      'Powoli opuść pięty.'],
    tips: ['Pełny zakres ruchu. Na stopniu możesz opuścić pięty niżej.'],
  },
  'wyciag-prostowanie': {
    kg: 2.5,
    name: 'Prostowanie ramion na wyciągu', p: ['triceps'], s: ['forearms', 'abs'],
    steps: ['Stań twarzą do wyciągu, linka z górnego bloczka. Chwyć drążek albo linę nachwytem.',
      'Łokcie przyciśnij do boków, przedramiona mniej więcej poziomo. Tułów lekko pochylony, brzuch napięty.',
      'Wyprostuj ręce w dół do pełnego wyprostu w łokciach, pół sekundy pauzy.',
      'Powoli wróć do poziomu, łokcie cały czas w tym samym miejscu.'],
    tips: ['Ruszają się tylko przedramiona. Jeśli łokcie uciekają do przodu albo pomagasz sobie tułowiem, zmniejsz ciężar.'],
  },
  'przysiad-sztanga': {
    kg: 2.5,
    name: 'Przysiad ze sztangą', p: ['quads', 'glutes'], s: ['hamstrings', 'adductors', 'lowerback', 'abs'],
    steps: ['Sztanga na górze pleców (nie na karku), chwyt trochę szerzej niż barki. Stopy na szerokość bioder lub trochę szerzej, palce lekko na zewnątrz.',
      'Weź oddech, napnij brzuch. Biodra w tył i w dół, kolana idą w kierunku palców.',
      'Zejdź tak nisko, jak utrzymasz proste plecy, najlepiej udo do poziomu lub niżej.',
      'Wstań, wypychając podłogę całą stopą. Wydech na górze.'],
    tips: ['Pięty cały czas na ziemi, kolana nie uciekają do środka.', 'Pierwsze tygodnie: lekko, technika ważniejsza od ciężaru.'],
  },
  'przysiad-goblet': {
    kg: 1,
    name: 'Przysiad z hantlem (goblet)', p: ['quads', 'glutes'], s: ['adductors', 'abs'],
    steps: ['Trzymaj hantel pionowo przy mostku, łokcie w dół.',
      'Stopy trochę szerzej niż biodra, palce lekko na zewnątrz.',
      'Zejdź głęboko między kolana, tułów wyprostowany.',
      'Wstań, wypychając podłogę całą stopą.'],
    tips: ['Dobre pierwsze ćwiczenie na naukę przysiadu: ciężar z przodu pomaga trzymać plecy prosto.'],
  },
  'martwy-rumunski': {
    kg: 1, kgOpis: 'na hantel',
    name: 'Martwy ciąg rumuński z hantlami', p: ['hamstrings', 'glutes'], s: ['lowerback', 'forearms'],
    steps: ['Stań prosto z hantlami przed udami, stopy na szerokość bioder, kolana lekko ugięte.',
      'Przesuwaj biodra w tył, hantle jadą blisko nóg. Plecy proste przez cały ruch.',
      'Zejdź do połowy goleni albo do momentu, gdy czujesz mocne rozciąganie z tyłu ud.',
      'Wróć, wypychając biodra do przodu i napinając pośladki.'],
    tips: ['To ruch bioder, nie pleców: kolana zostają w tym samym ugięciu.', 'Jeśli plecy się zaokrąglają, skróć zakres.'],
  },
  'hip-thrust': {
    kg: 2.5,
    name: 'Hip thrust ze sztangą', p: ['glutes'], s: ['hamstrings', 'quads'],
    steps: ['Oprzyj łopatki o krawędź ławki, sztanga na biodrach (z podkładką), stopy na ziemi na szerokość bioder.',
      'Napnij brzuch i wypchnij biodra w górę, aż tułów i uda będą w jednej linii.',
      'Na górze ściśnij pośladki, sekunda pauzy, broda lekko w stronę klatki.',
      'Opuść biodra pod kontrolą, prawie do ziemi.'],
    tips: ['Na górze golenie mniej więcej pionowo: jeśli nie, przesuń stopy.', 'Nie wyginaj lędźwi w łuk: ruch kończą pośladki.'],
  },
  'wyciskanie-lezac': {
    kg: 2.5,
    name: 'Wyciskanie sztangi leżąc', p: ['chest'], s: ['triceps', 'shoulders'],
    steps: ['Połóż się na ławce, oczy pod sztangą, stopy mocno na ziemi. Ściągnij łopatki.',
      'Chwyt trochę szerzej niż barki. Zdejmij sztangę i trzymaj ją nad barkami na prostych rękach.',
      'Opuść sztangę pod kontrolą do dolnej części klatki, łokcie lekko przy tułowiu.',
      'Wyciśnij do prostych rąk.'],
    tips: ['Przy większym ciężarze zawsze z asekuracją.', 'Pośladki i łopatki cały czas na ławce.'],
  },
  'wyciskanie-hantli-nad-glowe': {
    kg: 1, kgOpis: 'na hantel',
    name: 'Wyciskanie hantli nad głowę', p: ['shoulders'], s: ['triceps', 'traps', 'abs'],
    steps: ['Stań stabilnie, hantle na wysokości barków, łokcie lekko przed tułowiem.',
      'Napnij brzuch i pośladki.',
      'Wyciśnij hantle w górę do prostych rąk nad głową.',
      'Opuść powoli do barków.'],
    tips: ['Nie odchylaj się do tyłu: tułów zostaje prosto.', 'Można też siedząc na ławce z oparciem.'],
  },
  'wioslowanie-hantlem': {
    kg: 1,
    name: 'Wiosłowanie hantlem jednorącz', p: ['lats', 'midback'], s: ['biceps', 'forearms'],
    steps: ['Oprzyj jedną rękę o ławkę, plecy proste, prawie poziomo. Hantel w drugiej ręce zwisa pod barkiem.',
      'Ciągnij łokieć w górę wzdłuż tułowia, hantel do biodra.',
      'Na górze ściągnij łopatkę, sekunda pauzy.',
      'Opuść hantel do pełnego wyprostu ręki. Po serii zmień stronę.'],
    tips: ['Tułów się nie obraca: ruch robi ręka i łopatka.'],
  },
  'sciaganie-drazka': {
    kg: 2.5,
    name: 'Ściąganie drążka wyciągu górnego', p: ['lats'], s: ['biceps', 'midback'],
    steps: ['Usiądź, uda pod wałkami. Chwyć drążek nachwytem, trochę szerzej niż barki.',
      'Lekko odchyl tułów, klatka do góry.',
      'Ściągnij drążek do górnej części klatki, łokcie w dół i w tył.',
      'Wróć powoli do prostych rąk.'],
    tips: ['Nie szarp tułowiem: zmniejsz ciężar, jeśli musisz się bujać.', 'Dobre przygotowanie do podciągania na drążku.'],
  },
  'wioslowanie-wyciag': {
    kg: 2.5,
    name: 'Wiosłowanie na wyciągu siedząc', p: ['midback', 'lats'], s: ['biceps', 'lowerback'],
    steps: ['Usiądź, stopy na podpórce, kolana lekko ugięte. Chwyć uchwyt, plecy proste.',
      'Przyciągnij uchwyt do brzucha, łokcie blisko tułowia.',
      'Ściągnij łopatki, sekunda pauzy.',
      'Wróć powoli do prostych rąk, bez zaokrąglania pleców.'],
    tips: ['Tułów prawie nieruchomy: ruch robią ręce i łopatki.'],
  },
  'wykroki-hantle': {
    kg: 1, kgOpis: 'na hantel',
    name: 'Wykroki z hantlami', p: ['quads', 'glutes'], s: ['hamstrings', 'adductors'],
    steps: ['Stań prosto z hantlami w opuszczonych rękach.',
      'Zrób duży krok do przodu i zejdź w dół, aż tylne kolano będzie tuż nad ziemią.',
      'Przednie kolano nad stopą, tułów prosto.',
      'Wróć do stania przednią nogą. Nogi na zmianę albo seria na jedną stronę.'],
    tips: ['Krok na tyle długi, żeby przednia pięta nie odrywała się od ziemi.'],
  },
  'unoszenie-bokiem': {
    kg: 1, kgOpis: 'na hantel',
    name: 'Unoszenie hantli bokiem', p: ['shoulders'], s: ['traps'],
    steps: ['Stań prosto, hantle przy udach, łokcie lekko ugięte.',
      'Unieś ręce bokiem do wysokości barków.',
      'Chwila pauzy, barki nisko, z dala od uszu.',
      'Opuść powoli.'],
    tips: ['Lekki ciężar i pełna kontrola: bez bujania tułowiem.'],
  },
  'uginanie-hantle': {
    kg: 1, kgOpis: 'na hantel',
    name: 'Uginanie ramion z hantlami', p: ['biceps'], s: ['forearms'],
    steps: ['Stań prosto, hantle w opuszczonych rękach, dłonie do przodu.',
      'Łokcie przy bokach. Ugnij ręce, hantle jadą do barków.',
      'Na górze napnij biceps.',
      'Opuść powoli do prostych rąk.'],
    tips: ['Łokcie zostają w miejscu, tułów się nie buja.'],
  },
};

// Wersja angielska (aplikacja po angielsku): nazwy mięśni oraz nazwa, kroki i wskazówki każdego ćwiczenia; kgOpis jak wyżej.
// Nowe ćwiczenie dostaje wpis także tutaj (`node logic.js` sprawdza, czy niczego nie brakuje).
globalThis.MUSCLES_EN = {
  chest: 'chest', shoulders: 'shoulders', biceps: 'biceps', triceps: 'triceps', forearms: 'fore\u00ADarms',
  abs: 'abs', obliques: 'obliques', traps: 'tra\u00ADpezius', lats: 'lats', midback: 'mid back',
  lowerback: 'lower back', glutes: 'glutes', quads: 'quadri\u00ADceps', hamstrings: 'ham\u00ADstrings',
  adductors: 'adduc\u00ADtors', calves: 'calves',
};
Object.entries({
  'podciaganie': {
    name: 'Pull-up (overhand grip)',
    steps: ['Overhand grip, slightly wider than your shoulders. Start from a full hang, elbows straight.',
      'First pull your shoulder blades down, then drive your elbows towards your ribs.',
      'Chin over the bar, chest close to the bar.',
      'Lower yourself under control all the way to a full hang.'],
    tips: ['No swinging or kicking: legs together, abs and glutes tight.',
      'Only a full rep counts, from straight elbows to chin over the bar.'],
  },
  'podciaganie-podchwyt': {
    name: 'Chin-up (underhand grip)',
    steps: ['Underhand grip (palms facing you), shoulder-width apart, full hang.',
      'Pull your shoulder blades down and drive your elbows down along your body.',
      'Chin over the bar, half-second pause.',
      'Slowly return to a full hang.'],
    tips: ['Usually easier than the overhand grip, good for building up your reps.'],
  },
  'podciaganie-guma': {
    name: 'Band-assisted pull-up',
    steps: ['Tie the band to the bar (loop through loop) and put your foot or knee in it.',
      'Grip as in a regular pull-up (overhand or underhand, see the note), full hang.',
      'Pull yourself up, chin over the bar.',
      'Lower yourself slowly, over 2–3 s.'],
    tips: ['Choose a band that makes the last 2 reps hard but clean.',
      'Every few weeks switch to a thinner band. Goal: pull-ups with no help.'],
  },
  'podciaganie-negatyw': {
    name: 'Negative pull-up',
    steps: ['Get above the bar with a jump or from a box, chin over the bar.',
      'Lower yourself as slowly as you can (goal: 5 s) all the way to a full hang.',
      'Stand, take a breath and repeat.'],
    tips: ['Control the whole range, including the end with straight elbows.',
      "If you can't keep the tempo, cut the set short rather than dropping down."],
  },
  'podciaganie-lopatek': {
    name: 'Scapular pull-up',
    steps: ['Full hang with an overhand grip. Elbows stay straight for the whole exercise.',
      'Pull your shoulder blades down and back; your body rises a few centimetres.',
      'Hold for 1 s and slowly return to the hang.'],
    tips: ['Move only your shoulder blades, without bending your elbows.',
      'The foundation of healthy shoulders and clean pull-ups.'],
  },
  'zwis': {
    name: 'Dead hang',
    steps: ['Grab the bar with an overhand grip, shoulder-width apart.',
      'Hang on straight arms, legs together.',
      'Breathe calmly and hold until the time is up.'],
    tips: ['Active version: pull your shoulder blades down slightly, shoulders away from your ears.',
      'Builds grip strength and takes the load off your spine.'],
  },
  'trx-wioslowanie': {
    name: 'TRX row',
    steps: ['Hold the handles and lean back on straight arms, body straight as a plank.',
      'Squeeze your shoulder blades and pull your chest to your hands, elbows close to your body.',
      'One-second pause at the top, then slowly back to straight arms.'],
    tips: ['You set the difficulty with the angle: feet closer to the anchor point makes it harder.',
      "Hips don't sag, glutes tight."],
  },
  'wioslowanie-australijskie': {
    name: 'Australian row',
    steps: ['Lie under a low bar (at hip height) and grab it overhand, wider than your shoulders.',
      'Body straight from heels to head, heels on the ground.',
      'Pull your chest to the bar, squeezing your shoulder blades, and lower slowly.'],
    tips: ['Easier: bent knees. Harder: feet raised.'],
  },
  'dipy': {
    name: 'Parallel bar dip',
    steps: ['Support yourself on straight arms, shoulders down (away from your ears), legs slightly bent behind you.',
      'Lower yourself with your torso leaning slightly forward until your elbows bend to about 90°.',
      'Push back up until your elbows are fully straight.'],
    tips: ["Don't go lower than 90°, as that overloads your shoulders.",
      'Elbows go back, not out to the sides.'],
  },
  'dipy-negatyw': {
    name: 'Negative dip',
    steps: ['Get into a straight-arm support with a jump or from a box.',
      'Lower yourself slowly (goal: 4 s) until your elbows bend to about 90°.',
      'Stand, get back into the support and repeat.'],
    tips: ['Shoulders low for the whole movement.',
      'If you feel the front of your shoulder, shorten the range.'],
  },
  'podpor-porecze': {
    name: 'Parallel bar support hold',
    steps: ['Get up on the bars, arms straight, elbows locked.',
      'Shoulders pushed firmly down, chest forward, abs tight.',
      'Hold the position until the time is up.'],
    tips: ["Don't sink into your shoulders; keep your neck long.",
      'Prepares your shoulders and wrists for dips.'],
  },
  'pompki': {
    name: 'Push-up',
    steps: ['Hands slightly wider than your shoulders, body straight from head to heels.',
      'Lower your chest almost to the floor, elbows at about 45° to your body.',
      'Push back up to straight arms.'],
    tips: ["Abs and glutes tight, hips don't sag.",
      'Easier: hands raised. Harder: feet raised.'],
  },
  'pompki-trx': {
    name: 'TRX push-up',
    steps: ['Hold the handles, stand facing away from the anchor and lean forward with straight arms in front of your chest.',
      'Body straight. Bend your elbows until your hands are next to your chest.',
      'Push back to the start, keeping the handles from drifting apart.'],
    tips: ['The more horizontal you are, the harder it gets.',
      'Controlling the wobbly handles is the whole point of this exercise.'],
  },
  'pompki-waskie': {
    name: 'Close-grip push-up',
    steps: ['Hands under your shoulders or closer, fingers pointing forward.',
      'Lower yourself with your elbows close to your body.',
      'Push back up to straight arms.'],
    tips: ['Works your triceps harder, which prepares you for dips.',
      "Don't flare your elbows out to the sides."],
  },
  'pompki-nogi-wyzej': {
    name: 'Decline push-up',
    steps: ['Feet on a bench or box, hands on the floor wider than your shoulders.',
      'Body straight, lower your chest to the floor.',
      'Push back up to straight arms.'],
    tips: ['The higher your feet, the more your shoulders work.', "Don't bend at the hips."],
  },
  'pompki-na-podwyzszeniu': {
    name: 'Incline push-up',
    steps: ['Hands on a bench or box, body straight, feet on the floor.',
      'Lower your chest to the edge, elbows at about 45°.',
      'Push back up to straight arms.'],
    tips: ['An easier push-up: the higher your hands, the easier it is.'],
  },
  'guma-rozciaganie': {
    name: 'Band pull-apart',
    steps: ['Hold the band in front of you at shoulder height, arms straight, hands shoulder-width apart.',
      'Pull the band apart to the sides, squeezing your shoulder blades, until it touches your chest.',
      'Return slowly.'],
    tips: ["Shoulders low, don't lift them towards your ears.", 'Great for warming up and for posture.'],
  },
  'guma-rotacja': {
    name: 'Band external rotation',
    steps: ['Attach the band at elbow height and stand side-on to it.',
      'Elbow at your side (you can tuck a rolled-up towel under it), bent at 90°.',
      'Rotate your forearm outwards without moving your elbow away, then return slowly.'],
    tips: ['Light resistance: this exercise protects your shoulders, it is not for strength.',
      'One set with one arm, then the other.'],
  },
  'guma-odwrotne-rozpietki': {
    name: 'Band reverse fly',
    steps: ['Attach the band in front of you at chest height or hold both of its ends.',
      'Arms slightly bent. Open them out to the sides, squeezing your shoulder blades.',
      'One-second pause, then return slowly.'],
    tips: ["Works the back of your shoulders. Don't help yourself by leaning back."],
  },
  'kolana-porecze': {
    name: 'Knee raise on parallel bars',
    steps: ['Support yourself on straight arms on the parallel bars.',
      'Raise your knees to your chest, tucking your pelvis slightly.',
      'Lower your legs slowly, without swinging.'],
    tips: ['Shoulders low for the whole exercise.', 'Harder version: straight legs.'],
  },
  'kolana-zwis': {
    name: 'Hanging knee raise',
    steps: ['Hang from the bar, shoulder blades pulled slightly down.',
      'Raise your knees to your chest, tucking your pelvis.',
      'Lower slowly, without swinging.'],
    tips: ['If you start swinging, pause briefly at the bottom.',
      'Next step: straight legs up to horizontal.'],
  },
  'plank': {
    name: 'Plank',
    steps: ['Rest on your forearms, elbows under your shoulders.',
      'Body straight from head to heels, glutes and abs tight.',
      'Hold, breathing calmly.'],
    tips: ['Hips neither sag nor rise.',
      'Better shorter, but in perfect position.'],
  },
  'deska-bokiem': {
    name: 'Side plank',
    steps: ['Lie on your side, elbow under your shoulder, legs straight, one on top of the other.',
      'Lift your hips so that your body forms one straight line.',
      'Hold, and switch sides in the next set.'],
    tips: ["Hips pushed forward, glutes don't drift back."],
  },
  'trx-rollout': {
    name: 'TRX rollout',
    steps: ['Hold the handles and stand facing away from the anchor. Arms straight in front of you, straps taut.',
      'Lean forward, raising your straight arms overhead. Body straight as a plank.',
      'Return to the start using your abs.'],
    tips: ["Don't arch your lower back; abs and glutes tight.",
      'The difficulty depends on the angle. Start more upright.'],
  },
  'trx-kolana': {
    name: 'TRX knee tuck',
    steps: ['Feet in the TRX loops, straight-arm support as for a push-up.',
      'Pull your knees to your chest, raising your hips slightly.',
      'Return to the straight position under control.'],
    tips: ["Shoulders over your hands. In the starting position your hips don't sag."],
  },
  'dead-bug': {
    name: 'Dead bug',
    steps: ['Lie on your back, arms up, hips and knees bent at 90°.',
      'Press your lower back into the floor.',
      'Lower the opposite arm and leg at the same time, come back and switch sides.'],
    tips: ['Keep your lower back pressed into the floor the whole time. That is what this exercise is about.'],
  },
  'przysiad': {
    name: 'Squat',
    steps: ['Feet hip- or shoulder-width apart, toes turned slightly out.',
      'Go down by pushing your hips back, knees tracking over your toes.',
      'Go down at least until your thighs are level, then stand up, pressing through your whole feet.'],
    tips: ['Heels on the ground, back straight.'],
  },
  'przysiad-guma': {
    name: 'Band squat',
    steps: ['Stand on the band and hold the other end at your shoulders.',
      'Squat as usual: hips back, knees tracking over your toes.',
      'Stand up powerfully. The band resists the most at the top.'],
    tips: ['A thicker band or a shorter grip gives more resistance.'],
  },
  'trx-przysiad-wykroczny': {
    name: 'TRX split squat',
    steps: ['Stand facing away from the anchor, one foot in the TRX loop behind you.',
      'Bend your front leg while your back leg moves back in the loop. Torso leaning slightly forward.',
      'Push back up with your front leg. A full set on one leg, then the other.'],
    tips: ['Front knee over your foot, not caving in.',
      'Your weight is on the front leg; the back leg only helps you balance.'],
  },
  'przysiad-jednonoz': {
    name: 'Single-leg box squat',
    steps: ['Stand on one leg on the edge of a bench or box, the other leg hanging free.',
      'Hold on to a TRX or a post for balance.',
      'Slowly lower yourself on one leg as far as you can control, then stand up.'],
    tips: ['Knee over your toes, heel on the surface.',
      'This is the road to the pistol squat. Over time, help yourself less and less with your hands.'],
  },
  'wykroki': {
    name: 'Walking lunge',
    steps: ['Take a big step forward and lower your back knee almost to the ground.',
      'Push off with your front leg and take the next step with the other leg.',
      'Torso upright, legs alternating.'],
    tips: ['Front knee over your foot, not caving in.'],
  },
  'mostek': {
    name: 'Glute bridge',
    steps: ['Lie on your back, knees bent, feet close to your glutes.',
      'Lift your hips, squeezing your glutes hard, until your body forms a line from knees to shoulders.',
      'One-second pause, then slowly down.'],
    tips: ["Your glutes do the work, not your lower back. Don't arch your back."],
  },
  'mostek-jednonoz': {
    name: 'Single-leg glute bridge',
    steps: ['Like the glute bridge, but with one leg straight up in the air.',
      'Lift your hips, pushing through the heel of your supporting leg. Hips level.',
      'One-second pause, then slowly down. One set on one leg, then the other.'],
    tips: ["Your pelvis doesn't tilt to the side."],
  },
  'guma-sklon': {
    name: 'Band good morning',
    steps: ['Stand on the band and put the other end behind your neck, across your shoulders.',
      'Knees slightly bent. Lean your torso forward with a straight back (the movement comes from your hips).',
      'Come back upright, squeezing your glutes.'],
    tips: ["Back straight the whole time; don't round it.",
      'Feeling a stretch at the back of your thighs is normal here.'],
  },
  'guma-uginanie-nog': {
    name: 'Band leg curl',
    steps: ['Attach the band low in front of you, put the loop around your ankles and sit on a bench.',
      'Bend your knees, pulling your heels underneath you.',
      'Slowly return to straight legs.'],
    tips: ['You can also do it lying on your stomach, or on your back with your feet in a TRX.'],
  },
  'lydki-guma': {
    name: 'Band calf raise',
    steps: ['Stand on the band with the balls of your feet and hold its ends at your shoulders.',
      'Rise high onto your toes, one-second pause.',
      'Slowly lower your heels.'],
    tips: ['Full range of motion. On a step you can lower your heels further.'],
  },
  'wyciag-prostowanie': {
    name: 'Cable triceps pushdown',
    steps: ['Face the cable machine, cable on the high pulley. Grab the bar or rope with an overhand grip.',
      'Elbows pressed to your sides, forearms roughly horizontal. Torso leaning slightly forward, abs tight.',
      'Push your hands down until your elbows are fully straight, half-second pause.',
      'Slowly return to horizontal, elbows staying in the same place the whole time.'],
    tips: ['Only your forearms move. If your elbows drift forward or you help with your torso, lower the weight.'],
  },
  'przysiad-sztanga': {
    name: 'Barbell back squat',
    steps: ['Bar on your upper back (not on your neck), grip slightly wider than your shoulders. Feet hip-width or a little wider, toes turned slightly out.',
      'Take a breath and brace your abs. Hips back and down, knees tracking over your toes.',
      'Go as low as you can while keeping your back straight, ideally thighs level or lower.',
      'Stand up, pushing the floor away with your whole foot. Breathe out at the top.'],
    tips: ["Heels on the ground the whole time, knees don't cave in.", 'First weeks: go light, technique matters more than weight.'],
  },
  'przysiad-goblet': {
    name: 'Goblet squat',
    steps: ['Hold a dumbbell upright against your chest, elbows pointing down.',
      'Feet slightly wider than your hips, toes turned slightly out.',
      'Squat deep between your knees, torso upright.',
      'Stand up, pushing the floor away with your whole foot.'],
    tips: ['A good first exercise for learning to squat: the weight in front helps keep your back straight.'],
  },
  'martwy-rumunski': {
    kgOpis: 'per dumbbell',
    name: 'Dumbbell Romanian deadlift',
    steps: ['Stand tall with the dumbbells in front of your thighs, feet hip-width apart, knees slightly bent.',
      'Push your hips back, the dumbbells sliding close to your legs. Back straight for the whole movement.',
      'Go down to mid-shin or until you feel a strong stretch at the back of your thighs.',
      'Come back up by driving your hips forward and squeezing your glutes.'],
    tips: ['This is a hip movement, not a back one: your knees keep the same bend.', 'If your back starts to round, shorten the range.'],
  },
  'hip-thrust': {
    name: 'Barbell hip thrust',
    steps: ['Rest your shoulder blades on the edge of a bench, bar across your hips (with a pad), feet on the floor hip-width apart.',
      'Brace your abs and drive your hips up until your torso and thighs are in one line.',
      'At the top squeeze your glutes, one-second pause, chin slightly towards your chest.',
      'Lower your hips under control, almost to the floor.'],
    tips: ['At the top your shins should be roughly vertical: if not, move your feet.', "Don't arch your lower back: your glutes finish the movement."],
  },
  'wyciskanie-lezac': {
    name: 'Barbell bench press',
    steps: ['Lie on the bench with your eyes under the bar, feet firmly on the floor. Squeeze your shoulder blades together.',
      'Grip slightly wider than your shoulders. Unrack the bar and hold it over your shoulders on straight arms.',
      'Lower the bar under control to your lower chest, elbows slightly tucked in.',
      'Press back up to straight arms.'],
    tips: ['With heavier weights always have a spotter.', 'Glutes and shoulder blades stay on the bench the whole time.'],
  },
  'wyciskanie-hantli-nad-glowe': {
    kgOpis: 'per dumbbell',
    name: 'Dumbbell overhead press',
    steps: ['Stand steady, dumbbells at shoulder height, elbows slightly in front of your body.',
      'Brace your abs and glutes.',
      'Press the dumbbells up to straight arms overhead.',
      'Lower them slowly to your shoulders.'],
    tips: ["Don't lean back: your torso stays upright.", 'You can also do it seated on a bench with a backrest.'],
  },
  'wioslowanie-hantlem': {
    name: 'One-arm dumbbell row',
    steps: ['Rest one hand on a bench, back straight, almost horizontal. The dumbbell in your other hand hangs under your shoulder.',
      'Pull your elbow up along your body, dumbbell to your hip.',
      'At the top squeeze your shoulder blade, one-second pause.',
      'Lower the dumbbell until your arm is fully straight. Switch sides after the set.'],
    tips: ["Your torso doesn't rotate: your arm and shoulder blade do the work."],
  },
  'sciaganie-drazka': {
    name: 'Lat pulldown',
    steps: ['Sit with your thighs under the pads. Grab the bar overhand, slightly wider than your shoulders.',
      'Lean back slightly, chest up.',
      'Pull the bar down to your upper chest, elbows down and back.',
      'Slowly return to straight arms.'],
    tips: ["Don't jerk with your torso: lower the weight if you have to swing.", 'Good preparation for pull-ups on a bar.'],
  },
  'wioslowanie-wyciag': {
    name: 'Seated cable row',
    steps: ['Sit with your feet on the footrest, knees slightly bent. Grab the handle, back straight.',
      'Pull the handle to your stomach, elbows close to your body.',
      'Squeeze your shoulder blades, one-second pause.',
      'Slowly return to straight arms without rounding your back.'],
    tips: ['Torso almost still: your arms and shoulder blades do the work.'],
  },
  'wykroki-hantle': {
    kgOpis: 'per dumbbell',
    name: 'Dumbbell lunge',
    steps: ['Stand tall with the dumbbells in your hands, arms down.',
      'Take a big step forward and go down until your back knee is just above the floor.',
      'Front knee over your foot, torso upright.',
      'Push back to standing with your front leg. Alternate legs or do a full set on one side.'],
    tips: ["Take a step long enough that your front heel doesn't lift off the floor."],
  },
  'unoszenie-bokiem': {
    kgOpis: 'per dumbbell',
    name: 'Dumbbell lateral raise',
    steps: ['Stand tall, dumbbells by your thighs, elbows slightly bent.',
      'Raise your arms out to the sides up to shoulder height.',
      'Brief pause, shoulders low, away from your ears.',
      'Lower slowly.'],
    tips: ['Light weight and full control: no swinging your torso.'],
  },
  'uginanie-hantle': {
    kgOpis: 'per dumbbell',
    name: 'Dumbbell biceps curl',
    steps: ['Stand tall, dumbbells in your hands, arms down, palms facing forward.',
      'Elbows at your sides. Curl the dumbbells up towards your shoulders.',
      'Squeeze your biceps at the top.',
      'Lower slowly to straight arms.'],
    tips: ["Elbows stay in place, your torso doesn't swing."],
  },
}).forEach(([id, en]) => { EXERCISES[id].en = en; });
