// Napisy interfejsu: polski (domyślnie) i angielski. t('klucz', ...argumenty); wartość może być funkcją (liczby, odmiana).
// Język ustawia setLang() w index.html (localStorage 'jezyk'). Tekst dla trenera i panel trenera zostają po polsku.
globalThis.LANG = 'pl';
// Polska odmiana liczebników: 1 ćwiczenie, 2 ćwiczenia, 5 ćwiczeń.
const plN = (n, one, few, many) => n === 1 ? one : n % 10 > 1 && n % 10 < 5 && (n % 100 < 12 || n % 100 > 14) ? few : many;
globalThis.STR = {
  pl: {
    brand: 'trening', brandResults: 'wyniki', yes: 'tak', cancel: 'anuluj', ok: 'ok', close: 'Zamknij', langTitle: 'język',
    gateTitle: 'kod dostępu', gateIntro: 'Wpisz swoje inicjały i kod od trenera. Wystarczy raz, potem aplikacja działa też bez zasięgu.',
    initials: 'Inicjały', initialsPh: 'np. JK', code: 'Kod', enter: 'wejdź',
    errEmpty: 'Wpisz inicjały i kod.', errTooMany: 'Za dużo prób. Spróbuj za kilka minut.',
    errWrong: 'Inicjały albo kod się nie zgadzają. Sprawdź je albo napisz do trenera.',
    errOffline: 'Brak połączenia. Kod trzeba wpisać z dostępem do internetu.',
    codeExpired: 'Kod przestał działać. Wpisz go ponownie albo napisz do trenera.',
    surveyTitle: 'kilka pytań', surveyIntro: 'Z tych odpowiedzi trener ułoży Twój plan. Zaznacz to, co do Ciebie pasuje.',
    surveyFine: 'Odpowiedzi służą tylko do układania Twojego planu. Jeśli zechcesz je usunąć, napisz do trenera: z bazy znikną od razu, a z kopii zapasowych najpóźniej po 5 tygodniach.',
    surveySave: 'zapisz i przejdź dalej', surveyBack: 'wróć bez zmian', surveyMissing: 'Uzupełnij zaznaczone pytania.',
    surveyRange: (q, a, b) => `${q}: wpisz liczbę od ${a} do ${b}.`, surveyFail: 'Nie udało się zapisać. Sprawdź połączenie i spróbuj jeszcze raz.',
    surveySaved: 'Zapisano. Trener zobaczy zaktualizowaną ankietę.', surveyOffline: 'Ankietę można zmienić tylko z dostępem do internetu.',
    menu: 'Menu', menuImport: 'import', menuLib: 'ćwiczenia', menuHist: 'historia', menuSet: 'ustawienia',
    hello: n => `Hej, ${n}!`, changeName: 'Zmień imię', weekTabs: 'Treningi tygodnia',
    resumeDone: n => `${n}: niezapisane wyniki`, resumeRun: (n, i, k) => `W toku: ${n}, seria ${i} z ${k}`, resume: 'wznów', discard: 'porzuć',
    noPlanTitle: 'brak rozpiski', noPlanApi: 'Trener nie wysłał jeszcze rozpiski. Pojawi się tutaj sama.',
    noPlanLocal: 'Wczytaj rozpiskę od trenera: wklej jej tekst albo wybierz plik.', loadPlan: 'wczytaj rozpiskę',
    histRow: (d, n, r) => `${d} · ${n} · ${r} powt.`, histSend: 'wyślij ostatnie 10', histClear: 'wyczyść historię',
    histEmpty: 'Pusto. Zapisane treningi pojawią się tutaj.',
    nExercises: n => `${n} ${plN(n, 'ćwiczenie', 'ćwiczenia', 'ćwiczeń')}`, week: n => `tydzień ${n}`,
    sets: 'Serie', time: 'Czas', minutes: 'minut', lastTime: 'Ostatnio', repsOn: d => `powt. · ${d}`, none: 'brak',
    partLine: (s, g, r) => `${s} × ${g} · przerwa ${r}`, delWorkout: 'usuń ten trening', startN: n => `zacznij · ${n}`,
    exerciseList: 'Spis ćwiczeń', askDelWorkout: 'Usunąć ten trening?', del: 'usuń',
    askClearHist: 'Wyczyścić historię na tym telefonie? Wyniki, które poszły do trenera, zostają u niego.', clear: 'wyczyść',
    pager: (a, b, n) => `${a}–${b} z ${n}`,
    sheetImp: 'Import rozpiski', sheetLib: 'Biblioteka ćwiczeń', sheetHist: 'Historia', sheetAct: 'Trening', sheetUpd: 'Nowa wersja', sheetSet: 'Ustawienia',
    signedAs: w => `Zalogowano jako ${w}.`, surveyUpdate: 'zaktualizuj ankietę',
    surveyUpdateHint: 'Zmieniła się waga, cel albo coś boli? Popraw odpowiedzi, trener zobaczy nową ankietę.',
    logout: 'wyloguj się', logoutHint: 'Żeby wrócić, wpiszesz inicjały i kod od trenera. Rozpiska i wyniki zostają u trenera.',
    logoutQ: 'Wylogować się z tego telefonu?', logoutBusy: 'Trening w toku zostanie porzucony.',
    logoutQueued: n => `Niewysłane wyniki (${n}) wyślą się po ponownym wejściu tym samym kodem.`,
    updText: 'Jest nowsza wersja aplikacji. Historia i zapisane treningi zostają na miejscu.', update: 'zaktualizuj', later: 'później',
    skipEx: 'pomiń to ćwiczenie', quit: 'zakończ trening i pokaż wyniki',
    impPh: 'Wklej rozpiskę od trenera. Nowa rozpiska zastępuje poprzednią, historia treningów zostaje.', impLoad: 'wczytaj', impFile: 'z pliku',
    impFormat: 'format rozpiski', impOk: n => `Wczytano: ${n}`, impErr: m => `Nie da się wczytać: ${m}. Sprawdź, czy to cała rozpiska.`,
    impBad: 'to nie jest rozpiska w formacie aplikacji', copied: 'Skopiowano do schowka.', copyPrompt: 'Skopiuj:',
    nameTitle: 'jak masz na imię?', nameText: 'Aplikacja będzie się tak do Ciebie zwracać. Imię zostaje tylko na tym telefonie.',
    namePh: 'np. Ania', save: 'zapisz', noName: 'wolę bez imienia',
    how: 'jak wykonać', howTitle: 'Jak wykonać', video: 'Wideo z techniką na YouTube', videoQ: 'technika',
    legWork: 'spięty mięsień', legGear: 'sprzęt', legBand: 'guma', mainWork: 'główna praca', assist: 'pomocniczo', front: 'przód', back: 'tył',
    exOf: (i, n) => `ćwiczenie ${i} z ${n}`, target: 'Cel', set: 'Seria', rest: 'Przerwa', min: 'min', seconds: 'sekund', reps: 'powtórzeń',
    repsPer: x => `powt. · ${x}`, setDone: 'seria zrobiona', startTime: s => `start · ${s}\u00A0s`, weight: 'ciężar', perDumbbell: 'na hantel',
    workMenu: 'Menu treningu: pomiń ćwiczenie albo zakończ', less: 'Mniej', more: 'Więcej', lessKg: 'Mniejszy ciężar', moreKg: 'Większy ciężar',
    getReady: 'Przygotuj się', skip: 'pomiń', stop: 'stop', nextLine: (s, n, g) => `następnie · seria ${s}/${n} · ${g}`,
    repsT: 'Powtórzenia', firstTime: 'pierwszy raz', ofPlan: p => `${p}% planu`, hold: 'Napięcie', worked: 'Pracowały dziś',
    cmp: 'Porównanie z poprzednim', firstCmp: 'To pierwszy zapisany trening tego typu. Porównanie pojawi się następnym razem.',
    notes: 'Uwagi dla trenera', notesPh: 'Jak poszło, czy coś bolało, która guma…', textForTrainer: 'Tekst dla trenera',
    send: 'wyślij do trenera', saveHist: 'zapisz w historii i wróć', sending: 'wysyłam…', sent: 'wysłano', queued: 'zapisano, wyślę przy połączeniu',
    prevVal: v => `poprzednio ${v}`, howWas: 'jak było?', anyPain: 'coś bolało?', no: 'nie',
    rate_LEKKO: 'za lekko', rate_OK: 'w sam raz', rate_CIEZKO: 'za ciężko',
    painText: 'Zaznacz, co bolało. Trener zobaczy to razem z wynikami.', painTitle: 'co bolało?', done: 'gotowe',
    pain_BARKI: 'barki', pain_LOKCIE: 'łokcie', pain_NADGARSTKI: 'nadgarstki', pain_PLECY: 'plecy', pain_KOLANA: 'kolana', pain_BIODRA: 'biodra', pain_INNE: 'coś innego',
    askDiscard: 'Porzucić trening bez zapisu?', moveAria: 'Animacja ruchu',
  },
  en: {
    brand: 'training', brandResults: 'results', yes: 'yes', cancel: 'cancel', ok: 'OK', close: 'Close', langTitle: 'language',
    gateTitle: 'access code', gateIntro: 'Enter your initials and the code from your trainer. You only need to do it once; after that the app also works offline.',
    initials: 'Initials', initialsPh: 'e.g. JK', code: 'Code', enter: 'sign in',
    errEmpty: 'Enter your initials and code.', errTooMany: 'Too many attempts. Try again in a few minutes.',
    errWrong: "The initials or code don't match. Check them or contact your trainer.",
    errOffline: 'No connection. The code has to be entered while online.',
    codeExpired: 'Your code no longer works. Enter it again or contact your trainer.',
    surveyTitle: 'a few questions', surveyIntro: 'Your trainer will build your plan from these answers. Select what fits you.',
    surveyFine: "Your answers are used only to plan your training. If you want them deleted, tell your trainer: they're removed from the database straight away and from backups within 5 weeks.",
    surveySave: 'save and continue', surveyBack: 'back without changes', surveyMissing: 'Please answer the highlighted questions.',
    surveyRange: (q, a, b) => `${q}: enter a number from ${a} to ${b}.`, surveyFail: "Couldn't save. Check your connection and try again.",
    surveySaved: 'Saved. Your trainer will see the updated survey.', surveyOffline: 'You can only change the survey while online.',
    menu: 'Menu', menuImport: 'import', menuLib: 'exercises', menuHist: 'history', menuSet: 'settings',
    hello: n => `Hi, ${n}!`, changeName: 'Change name', weekTabs: "This week's workouts",
    resumeDone: n => `${n}: unsaved results`, resumeRun: (n, i, k) => `In progress: ${n}, set ${i} of ${k}`, resume: 'resume', discard: 'discard',
    noPlanTitle: 'no plan yet', noPlanApi: "Your trainer hasn't sent a plan yet. It will appear here on its own.",
    noPlanLocal: 'Load the plan from your trainer: paste its text or choose a file.', loadPlan: 'load plan',
    histRow: (d, n, r) => `${d} · ${n} · ${r} reps`, histSend: 'send last 10', histClear: 'clear history',
    histEmpty: 'Empty. Saved workouts will appear here.',
    nExercises: n => `${n} ${n === 1 ? 'exercise' : 'exercises'}`, week: n => `week ${n}`,
    sets: 'Sets', time: 'Time', minutes: 'minutes', lastTime: 'Last time', repsOn: d => `reps · ${d}`, none: 'none',
    partLine: (s, g, r) => `${s} × ${g} · rest ${r}`, delWorkout: 'delete this workout', startN: n => `start · ${n}`,
    exerciseList: 'Exercises', askDelWorkout: 'Delete this workout?', del: 'delete',
    askClearHist: 'Clear the history on this phone? Results already sent to your trainer stay with them.', clear: 'clear',
    pager: (a, b, n) => `${a}–${b} of ${n}`,
    sheetImp: 'Import plan', sheetLib: 'Exercise library', sheetHist: 'History', sheetAct: 'Workout', sheetUpd: 'New version', sheetSet: 'Settings',
    signedAs: w => `Signed in as ${w}.`, surveyUpdate: 'update survey',
    surveyUpdateHint: 'Has your weight or goal changed, or does something hurt? Update your answers and your trainer will see the new survey.',
    logout: 'sign out', logoutHint: 'To come back, enter your initials and the code from your trainer. Your plan and results stay with your trainer.',
    logoutQ: 'Sign out on this phone?', logoutBusy: 'The workout in progress will be discarded.',
    logoutQueued: n => `Unsent results (${n}) will be sent when you sign in again with the same code.`,
    updText: 'A newer version of the app is available. Your history and saved workouts stay where they are.', update: 'update', later: 'later',
    skipEx: 'skip this exercise', quit: 'finish workout and show results',
    impPh: 'Paste the plan from your trainer. A new plan replaces the previous one; your workout history stays.', impLoad: 'load', impFile: 'from file',
    impFormat: 'plan format', impOk: n => `Loaded: ${n}`, impErr: m => `Can't load it: ${m}. Check that this is the whole plan.`,
    impBad: "this isn't a plan in the app's format", copied: 'Copied to clipboard.', copyPrompt: 'Copy:',
    nameTitle: "what's your name?", nameText: 'The app will address you by this name. It stays on this phone only.',
    namePh: 'e.g. Anna', save: 'save', noName: 'no name, thanks',
    how: 'how to do it', howTitle: 'How to do it', video: 'Technique video on YouTube', videoQ: 'technique',
    legWork: 'working muscle', legGear: 'equipment', legBand: 'band', mainWork: 'main work', assist: 'assisting', front: 'front', back: 'back',
    exOf: (i, n) => `exercise ${i} of ${n}`, target: 'Target', set: 'Set', rest: 'Rest', min: 'min', seconds: 'seconds', reps: 'reps',
    repsPer: x => `reps · ${x}`, setDone: 'set done', startTime: s => `start · ${s}\u00A0s`, weight: 'weight', perDumbbell: 'per dumbbell',
    workMenu: 'Workout menu: skip an exercise or finish', less: 'Less', more: 'More', lessKg: 'Less weight', moreKg: 'More weight',
    getReady: 'Get ready', skip: 'skip', stop: 'stop', nextLine: (s, n, g) => `next · set ${s}/${n} · ${g}`,
    repsT: 'Reps', firstTime: 'first time', ofPlan: p => `${p}% of plan`, hold: 'Hold', worked: 'Worked today',
    cmp: 'Compared with last time', firstCmp: 'This is the first saved workout of this type. A comparison will appear next time.',
    notes: 'Notes for your trainer', notesPh: 'How did it go, did anything hurt, which band…', textForTrainer: 'Text for your trainer',
    send: 'send to trainer', saveHist: 'save to history and go back', sending: 'sending…', sent: 'sent', queued: 'saved, will send when online',
    prevVal: v => `previously ${v}`, howWas: 'how was it?', anyPain: 'anything hurt?', no: 'no',
    rate_LEKKO: 'too easy', rate_OK: 'just right', rate_CIEZKO: 'too hard',
    painText: 'Mark what hurt. Your trainer will see it with your results.', painTitle: 'what hurt?', done: 'done',
    pain_BARKI: 'shoulders', pain_LOKCIE: 'elbows', pain_NADGARSTKI: 'wrists', pain_PLECY: 'back', pain_KOLANA: 'knees', pain_BIODRA: 'hips', pain_INNE: 'something else',
    askDiscard: 'Discard this workout without saving?', moveAria: 'Movement animation',
  },
};
globalThis.t = (k, ...a) => { const v = STR[LANG]?.[k] ?? STR.pl[k]; return typeof v === 'function' ? v(...a) : v ?? k; };

// Ankieta: pytania przychodzą z serwisu po polsku; po angielsku pokazujemy je według id pytania i wartości odpowiedzi.
// Czego tu nie ma (np. nowe pytanie w serwisie), zostaje po polsku.
globalThis.SURVEY_EN = {
  plec: ['Sex', { K: 'female', M: 'male' }],
  wiek: ['Age'], wzrost: ['Height'], waga: ['Weight'],
  staz: ['How long have you been training regularly?', { BRAK: 'not at all', DO_6M: 'up to 6 months', DO_2L: '6 months – 2 years', PONAD_2L: 'over 2 years' }],
  cel: ['Main goal', { SILA: 'strength', MASA: 'muscle mass', SYLWETKA: 'better physique', REDUKCJA: 'weight loss', KONDYCJA: 'fitness and health', UMIEJETNOSCI: 'skills, e.g. pull-ups' }],
  partie: ['Which body parts matter most to you? (up to 2)', { KLATKA: 'chest', PLECY: 'back', BARKI: 'shoulders', RECE: 'arms', BRZUCH: 'abs', POSLADKI: 'glutes', NOGI: 'legs', CALE: 'whole body equally' }],
  rodzaj: ['What kind of training do you prefer?', { SILOWNIA: 'gym', KALISTENIKA: 'calisthenics', DOM: 'at home', OBA: 'varied, no preference' }],
  sprzet: ['What do you have access to?', { DRAZEK: 'pull-up bar', PORECZE: 'parallel bars', HANTLE: 'dumbbells', KETTLE: 'kettlebell', TRX: 'TRX', GUMY: 'resistance bands', BRAK: 'none of these' }],
  dni: ['How many days a week can you train?'],
  czas: ['How much time do you have for one workout?'],
  podciagniecia: ['How many clean pull-ups can you do?', { NIE_WIEM: "don't know" }],
  pompki: ['How many push-ups can you do?', { NIE_WIEM: "don't know" }],
  dipy: ['How many parallel bar dips can you do?', { NIE_WIEM: "don't know" }],
  bol: ['Does anything hurt, or have you had an injury?', { NIE: 'no', BARKI: 'shoulders', LOKCIE: 'elbows', NADGARSTKI: 'wrists', PLECY: 'back', KOLANA: 'knees', BIODRA: 'hips', INNE: 'something else' }],
  zgoda: ['I agree that my trainer may store these answers, including health information, and use them only to plan my training.', { true: 'agree' }],
};
globalThis.UNIT_EN = { lat: 'years', cm: 'cm', kg: 'kg' };
